[workspace]
members = [
  "coherence",
  "coherence-patch",
  "coherence-backend-traits",
  "coherence-backend-native",
  "coherence-backend-git",
  "coherence-backend-bzr",
  "coherence-backend-hg",
  "coherence-backend-jj",
  "coherence-backend-sl",
]
